### ISSUE TITLE
Babel 7 support

### ISSUE THREAD

**Issue by kettanaito** [timgrafton/babel-plugin-styled-components-postcss#5]
Current published version of this library doesn't seem to work with the latest release of Babel (`7.2.2`).  My dependencies:

```json
{
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.2.3",
    "@babel/plugin-proposal-export-default-from": "^7.2.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.2.0",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-typescript": "^7.1.0",
    "babel-core": "^7.0.0-bridge.0",
}
```

The usage of a lib results into exception:

```
ERROR in ./src/components/Box.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) CssSyntaxError: <css input>:2:3: Unknown word

  1 | 
> 2 |   __QUASI_EXPR_0__;
    |   ^
  3 |   display: __QUASI_EXPR_1__;
  4 | 

    at runLoaders (/Users/azakharchenko/libs/atomic-layout/node_modules/webpack/lib/NormalModule.js:298:13)
    at /Users/azakharchenko/libs/atomic-layout/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/azakharchenko/libs/atomic-layout/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/Users/azakharchenko/libs/atomic-layout/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/azakharchenko/libs/atomic-layout/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/Users/azakharchenko/libs/atomic-layout/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/azakharchenko/libs/atomic-layout/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/Users/azakharchenko/libs/atomic-layout/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.module.exports (/Users/azakharchenko/libs/atomic-layout/node_modules/tslint-loader/index.js:141:3)
 @ ./src/index.ts 3:0-50 3:0-50
```

I do understand that the published version demands explicit peer dependency, that include `babel-core` and Babel presets. However, is there any plan to make it work with the latest releases?

If you can briefly introduce me to what may be affected by updating the versions of peer dependencies, I can help with a pull request. Most likely the Babel plugin API will be changed.

Thank you.

**Comment by timgrafton** [comment]
Now Babel 7 compliant.
